ARG BASEIMG
ARG IMG_VERSION
FROM $BASEIMG:$IMG_VERSION
COPY . .
ARG SONAR_TOKEN
ARG SONAR_URL
ARG SONAR_PROJECT
ARG DOTNET_RUNTIME_IDENTIFIER

RUN dotnet sonarscanner begin \
  /k:"$SONAR_PROJECT" \
  /d:sonar.login="$SONAR_TOKEN" \ 
  /d:sonar.host.url="$SONAR_URL" \
  /d:sonar.coverageReportPaths="./sonarqubecoverage/SonarQube.xml" \
  /d:sonar.qualitygate.wait=true \
  /d:sonar.qualitygate.timeout=900 \
&& dotnet build -c Release -p:DOTNET_RUNTIME_IDENTIFIER=$(DOTNET_RUNTIME_IDENTIFIER) . \
&& dotnet test --no-build -c Release -p:DOTNET_RUNTIME_IDENTIFIER=$(DOTNET_RUNTIME_IDENTIFIER) --collect:'XPlat Code Coverage' --verbosity minimal --results-directory ./results \
&& reportgenerator "-reports:./results/*/coverage.cobertura.xml" "-targetdir:sonarqubecoverage" "-reporttypes:SonarQube" \
&& dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"